#!/usr/bin/env bash
#
# Sisoul clean-room build — 从 ~/sisoul-dev/ 拆出 4 个公开 repo, 跑脱敏, gh repo create (private).
#
# 不真 push, 留最后一步 `git push -u origin main` 给用户.
#
# 用法:
#   ops/release/clean-room-build.sh           # 真跑
#   ops/release/clean-room-build.sh --dry-run # 跑脱敏 dry-run, 不 git init, 不 gh create
#   ops/release/clean-room-build.sh --skip-gh # 跳过 gh repo create (适合先本地看一眼)
#
# Repo 拆分:
#   sisoul-cli       — src/ + tests/ + qa/ + pyproject.toml (CLI 主仓)
#   sisoul-protocol  — contracts/ + sdk/ + pip/ (协议 + 多语言 SDK)
#   sisoul-pip       — docs/pip/ + 安装脚本 (面向用户的 pip 包文档)
#   sisoul-docs      — docs/whitepaper/ + docs/ 其他 (公开 docs / whitepaper)

set -euo pipefail

DRY_RUN=0
SKIP_GH=0
ORG="${SISOUL_GH_ORG:-sisoul}"
BUILD_DIR="${SISOUL_BUILD_DIR:-/tmp/sisoul-release-build}"

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --skip-gh) SKIP_GH=1 ;;
    --help|-h)
      sed -n '1,30p' "$0"
      exit 0
      ;;
  esac
done

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BLACKLIST="$SCRIPT_DIR/desensitize-blacklist.yaml"
DESENSITIZE_PY="$SCRIPT_DIR/desensitize.py"

if [[ ! -f "$BLACKLIST" ]]; then
  echo "ERROR: blacklist not found at $BLACKLIST" >&2
  exit 2
fi

echo "============================================================"
echo "Sisoul clean-room build"
echo "  source       : $ROOT"
echo "  build dir    : $BUILD_DIR"
echo "  GitHub org   : $ORG"
echo "  dry-run      : $DRY_RUN"
echo "  skip-gh      : $SKIP_GH"
echo "============================================================"

# 1) 重置 build dir
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"/{sisoul-cli,sisoul-protocol,sisoul-pip,sisoul-docs}

# 2) rsync 内容到各子 repo (按规则拆)
rsync_to() {
  local target="$1"; shift
  local sources=("$@")
  for src in "${sources[@]}"; do
    if [[ ! -e "$ROOT/$src" ]]; then
      echo "  [warn] source missing: $src — skip"
      continue
    fi
    echo "  rsync $src → $target/"
    rsync -a \
      --exclude '.git/' \
      --exclude 'node_modules/' \
      --exclude '__pycache__/' \
      --exclude '.venv/' \
      --exclude 'dist/' \
      --exclude 'build/' \
      --exclude 'target/' \
      --exclude '*.pyc' \
      "$ROOT/$src" "$BUILD_DIR/$target/"
  done
}

echo "── stage sisoul-cli ────────────────────────────"
rsync_to sisoul-cli src tests qa pyproject.toml VERSION

echo "── stage sisoul-protocol ───────────────────────"
rsync_to sisoul-protocol contracts sdk
[[ -d "$ROOT/pip" ]] && rsync_to sisoul-protocol pip

echo "── stage sisoul-pip ────────────────────────────"
[[ -d "$ROOT/docs/pip" ]] && rsync_to sisoul-pip docs/pip
[[ -d "$ROOT/pip" ]] && rsync_to sisoul-pip pip

echo "── stage sisoul-docs ───────────────────────────"
[[ -d "$ROOT/docs/whitepaper" ]] && rsync_to sisoul-docs docs/whitepaper
# 公开 docs 整体也搬一份, 让脱敏来过滤. README-internal 不进 docs repo.
rsync -a --exclude '.git/' --exclude 'pip/' \
  "$ROOT/docs/" "$BUILD_DIR/sisoul-docs/docs/" 2>/dev/null || true

# 删除明确不该进 public 的入口文件
for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
  find "$BUILD_DIR/$repo" \
    \( -name 'README-internal.md' -o -name '*.private.*' -o -name 'CLAUDE.md' \) \
    -delete 2>/dev/null || true
done

# 3) 脱敏 - 每个 repo 独立跑
echo "── desensitize ──────────────────────────────────"
DESENSITIZE_FLAGS=()
[[ "$DRY_RUN" == "1" ]] && DESENSITIZE_FLAGS+=("--dry-run")

for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
  echo "  [$repo]"
  python3 "$DESENSITIZE_PY" \
    --root "$BUILD_DIR/$repo" \
    --config "$BLACKLIST" \
    --report "$BUILD_DIR/$repo/.desensitize-report.txt" \
    "${DESENSITIZE_FLAGS[@]}" || {
      echo "  [$repo] desensitize FAILED — check $BUILD_DIR/$repo/.desensitize-report.txt" >&2
      exit 1
    }
done

if [[ "$DRY_RUN" == "1" ]]; then
  echo
  echo "[dry-run] stopped before git init / gh create."
  echo "[dry-run] inspect $BUILD_DIR/*/.desensitize-report.txt then re-run without --dry-run."
  exit 0
fi

# 4) git init + initial commit 各 repo
echo "── git init + commit ────────────────────────────"
for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
  pushd "$BUILD_DIR/$repo" > /dev/null
  if [[ ! -d .git ]]; then
    git init -q -b main
  fi
  # .gitignore 兜底
  cat > .gitignore <<'EOF'
__pycache__/
*.pyc
.venv/
node_modules/
dist/
build/
target/
.desensitize-report.txt
.env
.env.*
EOF
  git add -A
  if git diff --cached --quiet; then
    echo "  [$repo] nothing to commit"
  else
    git commit -q -m "initial clean-room export

Generated by sisoul clean-room-build.sh
Desensitized via desensitize-blacklist.yaml"
    echo "  [$repo] commit OK"
  fi
  popd > /dev/null
done

# 5) gh repo create (private, 不 push)
if [[ "$SKIP_GH" == "0" ]]; then
  echo "── gh repo create (private, no push) ────────────"
  if ! command -v gh >/dev/null 2>&1; then
    echo "  [warn] gh CLI not found — skip repo create"
    SKIP_GH=1
  else
    for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
      pushd "$BUILD_DIR/$repo" > /dev/null
      if gh repo view "$ORG/$repo" >/dev/null 2>&1; then
        echo "  [$repo] $ORG/$repo already exists — skip create"
      else
        gh repo create "$ORG/$repo" --private --source=. --remote=origin || {
          echo "  [$repo] gh repo create failed — continue"
        }
      fi
      popd > /dev/null
    done
  fi
fi

# 6) 输出用户最后一步 push 命令
echo
echo "============================================================"
echo "DONE. Inspect each repo, then push manually:"
echo "============================================================"
for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
  echo "  cd $BUILD_DIR/$repo && git push -u origin main"
done
echo
echo "Desensitization reports:"
for repo in sisoul-cli sisoul-protocol sisoul-pip sisoul-docs; do
  echo "  $BUILD_DIR/$repo/.desensitize-report.txt"
done
